// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvklddouxabilqcckuyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2a2xkZG91eGFiaWxxY2NrdXlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MDE0ODYsImV4cCI6MjA2NzQ3NzQ4Nn0.P9NImT7knEoPzuNFbCv5kygdcsmXidWDxVugqK-yNo4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});